apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: my-flask-app
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: kind/challenge:a610b9cb6ea6b552848264453d09c7775dede16db51c93b4cc8426242a5bf364
