apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: web-chal-demo
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: kind/healthcheck:2b9b60a4a816c429b73451790dbf855e6fc29dd512adeed06d6381650f3e9b07
  image: kind/web-chal-demo:challenge
