"""Add columns IsStart, time_limit, and require_deploy to Challenges model

Revision ID: 1c51e6049fd1
Revises: 5e0c295c5859
Create Date: 2024-10-14 15:02:43.312075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c51e6049fd1'
down_revision = '5e0c295c5859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_challenge', sa.Column('image_name', sa.String(length=128), nullable=True))
    op.add_column('deploy_challenge', sa.Column('time_limit', sa.DateTime(), nullable=True))
    op.add_column('deploy_challenge', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'deploy_challenge', ['image_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deploy_challenge', type_='unique')
    op.drop_column('deploy_challenge', 'last_update')
    op.drop_column('deploy_challenge', 'time_limit')
    op.drop_column('deploy_challenge', 'image_name')
    # ### end Alembic commands ###
