"""Add IsStart column to Challenges model

Revision ID: 1f0b9d375b5f
Revises: ac4848cc407c
Create Date: 2024-10-14 14:44:31.260334

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f0b9d375b5f"
down_revision = "ac4848cc407c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deploy_challenge",
        sa.Column("image_name", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "deploy_challenge", sa.Column("time_limit", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "deploy_challenge", sa.Column("last_update", sa.DateTime(), nullable=True)
    )
    op.create_unique_constraint(None, "deploy_challenge", ["image_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deploy_challenge", type_="unique")
    op.drop_column("deploy_challenge", "last_update")
    op.drop_column("deploy_challenge", "time_limit")
    op.drop_column("deploy_challenge", "image_name")
    # ### end Alembic commands ###
