"""Add time_litmit column to Challenges model

Revision ID: ac4848cc407c
Revises: cf1e679b283d
Create Date: 2024-10-14 13:50:09.539429

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac4848cc407c"
down_revision = "cf1e679b283d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("time_limit", sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, "deploy_challenge", ["image_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "challenges", type_="unique")
    op.drop_column("challenges", "time_limit")
    # ### end Alembic commands ###
