"""Add deployed_challenge table

Revision ID: b221f2ee333d
Revises: fdcf76f05c45
Create Date: 2024-10-14 22:07:35.152135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b221f2ee333d'
down_revision = 'fdcf76f05c45'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('deployed_challenge')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployed_challenge',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('challenge_id', sa.INTEGER(), nullable=False),
    sa.Column('deploy_state', sa.TEXT(), nullable=False),
    sa.Column('image_name', sa.TEXT(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
