"""add new column

Revision ID: b2bf775c19f4
Revises: ec78ffb6edc1
Create Date: 2024-10-15 12:21:25.558312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bf775c19f4'
down_revision = 'ec78ffb6edc1'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.alter_column('deployed_challenge', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('deployed_challenge', 'user_id')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployed_challenge', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.alter_column('deployed_challenge', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
