"""Add isDeploy column to Challenges model

Revision ID: cf1e679b283d
Revises: 0b902d038903
Create Date: 2024-10-14 13:49:40.637638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1e679b283d'
down_revision = '0b902d038903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_challenge', sa.Column('image_name', sa.String(length=128), nullable=True))
    op.add_column('deploy_challenge', sa.Column('time_limit', sa.DateTime(), nullable=True))
    op.add_column('deploy_challenge', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'deploy_challenge', ['image_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deploy_challenge', type_='unique')
    op.drop_column('deploy_challenge', 'last_update')
    op.drop_column('deploy_challenge', 'time_limit')
    op.drop_column('deploy_challenge', 'image_name')
    # ### end Alembic commands ###
