"""Add deployment_name column to deployed_challenge

Revision ID: ec78ffb6edc1
Revises: c2ec83220933
Create Date: 2024-10-14 23:41:08.544799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec78ffb6edc1'
down_revision = 'c2ec83220933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.add_column('deployed_challenge', sa.Column('deployment_name', sa.String(length=255), nullable=True))
    op.alter_column('deployed_challenge', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployed_challenge', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('deployed_challenge', 'deployment_name')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
