"""update db

Revision ID: fdcf76f05c45
Revises: c45418df34c2
Create Date: 2024-10-14 15:39:08.307720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcf76f05c45'
down_revision = 'c45418df34c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'require_deploy')
    op.drop_column('challenges', 'isStart')
    op.drop_column('challenges', 'time_limit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('time_limit', sa.DATETIME(), nullable=True))
    op.add_column('challenges', sa.Column('isStart', sa.BOOLEAN(), server_default=sa.text('(False)'), nullable=True))
    op.add_column('challenges', sa.Column('require_deploy', sa.BOOLEAN(), server_default=sa.text('(False)'), nullable=True))
    # ### end Alembic commands ###
